### ISSUE TITLE
增加事件代办等级划分区功能

### ISSUE THREAD

**Issue by zzyweber** [path-yu/flutter_todo_client#1]
需求描述：用户日常代办应划分为紧急重要、紧急不重要、不重要紧急、不重要不紧急待办区

**Comment by webyang-male** [comment]
> 需求描述：用户日常代办应划分为紧急重要、紧急不重要、不重要紧急、不重要不紧急待办区
同意楼上，速更！ 🚀

**Comment by path-yu** [comment]
success
